server:
  port: 8081
  db:
    port: 5455

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:

  liquibase:
    change-log: classpath:liquibase/changelog.xml
    enabled: true
